SlideShow_skeleton cooking page
hungngodev/Flavorie pull request #20
Opened 2024-04-22 02:24 UTC by thuyvy119

Done issue #8: A slider with static slideshow that displays cooking steps including images and descriptions for each step in the cooking page:

- ChakraCarousel component with Slider (overall layout and positioning of the carousel), Track (render items in horizontal layout and Items components: 
  - Slider provides incrementing and decrementing buttons, use useBoundingRect hook to calculate the slider width.
  - Track handles drag and swipe gestures, uses framer motion library for animating the item's positions.
  - Item handles focus and blur events to update the active item state.

2024-04-23 00:19 UTC, hungngodev requested changes
Change a little bit at App.tsx

2024-04-23 00:19 UTC, hungngodev commented on client/src/App.tsx
> +    element: <ImageSlide />,
Change it to the original so we can merge it

2024-04-23 00:21 UTC, hungngodev reviewed
Everything is perfect!! Great jobbb ten thumbs up! However, I just want verify if it is working correctly so can you hop on Discord so we can discuss it? You can go on to the next task!

2024-04-23 04:01 UTC, hungngodev requested changes
A video of demo pleasee!

2024-04-23 04:28 UTC, thuyvy119 commented
> A video of demo pleasee!

Done nhe.

2024-04-27 16:03 UTC, hungngodev requested changes
Can you fix again the merge conflict?

2024-04-27 17:05 UTC, hungngodev approved these changes
Done

2024-04-28 02:02 UTC, hungngodev approved these changes
Doneee

2024-04-28 02:18 UTC, merged