Features/tag
hungngodev/Flavorie pull request #44
Opened 2024-05-10 18:25 UTC by viennguyen24

Resolve #29 

**CustomTag Component: (client\src\components\utils\tag.tsx)**
- This component extends the full Tag component from Chakra-ui [docs](https://v2.chakra-ui.com/docs/components/tag/usage) with custom props like closing / opening, handle click and handle close, and takes in Styled Props provided by Chakra-ui

**2 required props for this component: label (the content of the tag) and type ("diet" or "allergy"). I have attached a sample below:** 
`![image](https://github.com/hungngodev/Flavorie/assets/142319485/3894dcc7-3f28-46b1-a9fe-5bd0e8c2703e)

```typescript 
  <CustomTag label="diet" type="diet" />
  <CustomTag label="allergy" type="allergy" />
```

**You can also add other Styled Props into it:** 
![image](https://github.com/hungngodev/Flavorie/assets/142319485/eaa3db02-73d3-4bec-90b1-a5c5482e11ea)
```typescript
      <CustomTag label="diet" type="diet" w="10rem" mx="5rem" />
      <CustomTag label="allergy" type="allergy" h="6rem" border="1px" borderColor="red.500" />
```

**You can add some left / right element of your choice (note: add the import not the component itself)**
![image](https://github.com/hungngodev/Flavorie/assets/142319485/9e00a0b2-82b3-4382-b2f4-99bb17112802)
```typescript
import { BsApple } from 'react-icons/bs';
import { LuBanana } from 'react-icons/lu';
       ...
      <CustomTag label="diet" type="diet" leftElement={BsApple} />
      <CustomTag label="allergy" type="allergy" rightElement={LuBanana} />
```

**You can define your own onlick and onclose function and pass it as prop**

https://github.com/hungngodev/Flavorie/assets/142319485/488724e2-b1d7-4e97-a1c4-81d9a8860dca

```typescript
  const [openTag, setOpenTag] = useState<boolean>(true);

  const handleClick = () => {
    console.log('clicked!');
  };
  const handleClose = () => {
    setOpenTag(false);
  };

  return (
    <div>
      <CustomTag label="diet" type="diet" canClose={true} isOpen={openTag} handleClose={handleClose} />
      <CustomTag label="allergy" type="allergy" handleClick={handleClick} />
    </div>
  );
  ```

2024-05-11 03:02 UTC, hungngodev commented on client/src/components/meals/tag.tsx
> +    };
This is a good scheme

2024-05-19 00:49 UTC, hungngodev requested changes
Could you upload the latest UI? Good work

2024-05-19 05:27 UTC, viennguyen24 commented
> Could you upload the latest UI? I think you have not posted the latest one. I'm only seeing the tag component here.

Hi Hung, I just uploaded the new UI with some sample code!

2024-05-19 05:35 UTC, viennguyen24 commented on client/src/components/meals/tag.tsx
This file is an old version of the CustomTag but at the moment I cant find a way to remove this

2024-05-23 04:24 UTC, hungngodev requested changes
Please merge the conflict!

2024-05-23 04:24 UTC, hungngodev commented on client/src/components/meals/CustomTag.tsx
> +            boxShadow="md"
create a form for this!

2024-05-26 02:49 UTC, hungngodev requested changes
Please merge any remaining conflicts

2024-05-26 16:35 UTC, viennguyen24 commented
> Please merge any remaining conflicts

Hi Hung I just resolved all conflicts at [#76e2a42](https://github.com/hungngodev/Flavorie/pull/44/commits/76e2a42b1692c25a43860073cc7d00e66711b4dc)

2024-05-30 09:09 UTC, hoatuyet423 commented
- conflicts not fully resolved still

2024-05-31 02:13 UTC, hungngodev approved these changes
Merging conflict done. Thankss

2024-05-31 02:15 UTC, merged