Features/receipt form
hungngodev/Flavorie pull request #49
Opened 2024-05-19 00:07 UTC by viennguyen24

**Resolve #39**
![image](https://github.com/hungngodev/Flavorie/assets/142319485/ccabda0b-9731-4fea-b7d7-f6cad101af7d)

**Files involved: client/src/pages/ReceiptForm.tsx**
This is a form page that updates data from back-end and dynamically renders each data as a form field with three sub fields including name, quantity, and price. 

- Users can press "Add new receipt" and manually enter information about a receipt, update current ones, and delete receipts by pressing the "Delete" button 
- The form dynamically tracks all data entered and will execute an onSubmit function (Submit changes button), right now the function only prints out all entered data

**Work to be done**
- Calling backend to retrieve receipts data and 
- Creating a state to manage current receipts and load current receipts, as well as to store data retrieved
- Break down some code into separate component to reuse in the future (if needed)

2024-05-19 00:20 UTC, hungngodev requested changes
Change the login to Login file

2024-05-19 03:39 UTC, hungngodev requested changes

2024-05-19 03:39 UTC, hungngodev commented on client/src/pages/mockReceipt.ts
> +};
Move this mock file into the ReceiptForm.tsx. Also the Receipt Form should be placed in the component folder not pages folder.

2024-05-19 03:39 UTC, hungngodev commented on client/src/pages/login.tsx
> +  .strict();
I have not seen the same for the Register page. Could you upload to this same PR?

2024-05-19 03:39 UTC, hungngodev commented on client/src/pages/MockReceipt.ts
Could you move this file with the ReceiptForm.tsx to the components folder?

2024-05-19 06:18 UTC, viennguyen24 commented on client/src/pages/ReceiptForm.tsx
This file is moved into components/ingredients folder

2024-05-19 06:26 UTC, viennguyen24 commented on client/src/pages/login.tsx
> +  .strict();
Hi Hung, I uploaded both the Register and Login page at commit #[b2e3a42](https://github.com/hungngodev/Flavorie/pull/49/commits/b2e3a427abeaa7b2ec569b5c77b5d93dd927ff45)!

2024-05-19 06:27 UTC, viennguyen24 commented on client/src/pages/MockReceipt.ts
> Could you move this file with the ReceiptForm.tsx to the components folder?

Check commit #[7820fba](https://github.com/hungngodev/Flavorie/pull/49/commits/7820fba3cfa249047c060da06faae58a18eb0da9) !

2024-05-21 08:28 UTC, hoatuyet423 commented
- Confused, is this branch suppose to resolve 2 issues? Only one is mentioned in the description. If yes, then should not do this in the future, only 1 PR per 1 branch per issue. 
- A lot of styling in the code is really inconsistent. For example how your css is structures is different in different files and places in your code. 
- I didnt read much about the html as it will mostly shown in the UI, but leave a few comments here and there
- Can you provide a video of interaction with the UI and what it does?
- NIT: I feel like the huge space in between the item card is making it feel empty. Can make the order summary card bigger to balance this out 
- Overall UI look nice and clean, but feel like the code is still pretty confused to follow .-. Good works tho :>

2024-05-30 09:12 UTC, hoatuyet423 commented
- resolved conflict 
- demo link doesnt work

2024-06-05 02:18 UTC, closed without merging