#37 Horizontal list of meal card
hungngodev/Flavorie pull request #52
Opened 2024-05-20 03:26 UTC by thuyvy119

Close #37 Horizontal list of meal card
- Added ListofMeals component.
- Adjusted ImageCard component: added infoLink in See more button and set card variant to outline.
- Create a mock data function to render the Meal page.

https://github.com/hungngodev/Flavorie/assets/45311428/77f6d91b-9764-47a2-a119-de5154ed1fb1

2024-05-20 03:41 UTC, hungngodev requested changes

2024-05-20 03:41 UTC, hungngodev commented on client/src/components/meals/ListofMeals.tsx
> +                    />
Please make the card smaller!

2024-05-20 03:41 UTC, hungngodev commented on client/src/components/meals/ImageCard.tsx
Please make a 1 line description for this one!

2024-05-20 18:03 UTC, thuyvy119 commented on client/src/components/meals/ImageCard.tsx
Updated list as below
https://github.com/hungngodev/Flavorie/assets/45311428/ff20571f-1268-4f6f-9bcb-a874886a2b2f

2024-05-20 18:04 UTC, thuyvy119 commented
Updated list as below

https://github.com/hungngodev/Flavorie/assets/45311428/32d2bbc2-94d8-4059-9f0a-f9c013f9cbaa

2024-05-21 07:57 UTC, hoatuyet423 commented
- Code look pretty good in general
- add more spacing between each horizontal block
- Make the tittle (for example "Meal 1", "Meal 2') more clear, either bold them or make them bigger, make sure that the seperation is clear for the user. Also this is personal but i feel like it would look better without the box around the tittle, since this page already have so many boxes .-.
- Color and the theme need to be change too but those can be decided later
- Otherwise everything look pretty good to me. Great works!

2024-05-21 20:57 UTC, hungngodev requested changes
Please fixing Jenny's comment by today!

2024-05-22 04:51 UTC, thuyvy119 commented
Thank you Jenny for your comment, already added more spacing and change font size for title of each meal type.

https://github.com/hungngodev/Flavorie/assets/45311428/2627d975-112f-470b-b075-287b1d0df117

2024-05-22 21:07 UTC, hungngodev approved these changes
Great work!!!

2024-05-22 21:08 UTC, merged