Refactor receipt form into seperate components for reusability
hungngodev/Flavorie pull request #62
Opened 2024-05-30 03:46 UTC by viennguyen24

2024-05-30 09:18 UTC, hungngodev requested changes
Merge the conflict please!

2024-05-30 09:41 UTC, hoatuyet423 commented
- Love the new UI!!!
- The pencil icon for AI suggestion is not intuitive, change it to something more uinversal (like a star or a box that said suggestion or you can also just keep the suggestion box you have right now and have it show without clicking the pencil icon)
- NIT: Add a line or a very light border to seperate each ingredients will make it look better.

2024-06-06 03:16 UTC, hungngodev requested changes
Please update the latest UI review comment today!

2024-06-06 03:35 UTC, hungngodev requested changes

2024-06-06 03:35 UTC, hungngodev commented on client/src/components/ingredients/ReceiptForm.tsx
> +          Add new receipt
Change this to add new input

2024-06-06 03:35 UTC, hungngodev commented on client/src/components/ingredients/ReceiptField.tsx
> +    console.log(val);
Please make a mock API call to backend to help NA know. 
For example you could just write a line like 
const newData = await customFetch.get(something)
Do some update logic with the form to reflect it like modify the Options variable below or modify the field.suggested.item something.

2024-06-08 02:54 UTC, closed without merging